Iter13
msjai/url-shortener-service pull request #15
Opened 2023-01-08 09:50 UTC by msjai

2023-01-10 10:24 UTC, Bazys requested changes
1. goimports
2. linter
3. несколько вопросов

2023-01-10 10:24 UTC, Bazys commented on cmd/shortener/main.go
про goimport забыл.

2023-01-10 10:24 UTC, Bazys commented on internal/controller/shortener.go
>  	var reader io.Reader
зачем на 160 строчке `` кавычки? чем просто " не усчтраивает?

2023-01-10 10:24 UTC, Bazys commented on internal/controller/shortener.go
> +func getUserID(r *http.Request, w http.ResponseWriter, URLString string, cfg *config.Config) (string, bool, error) {
```suggestion
func getUserID(r *http.Request, w http.ResponseWriter, url string, cfg *config.Config) (string, bool, error) {
```
у тебя и так тип стринг, зачем это еще в названии указывать?

2023-01-10 10:24 UTC, Bazys commented on internal/controller/shortener.go
>  	longURLString := string(b[:])
зачем [:] ?

2023-01-10 10:24 UTC, Bazys commented on internal/usecase/repo/shortenerpostgres.go
> +func (d *PGRepoS) findMaxNumber(ctx context.Context, cfg *config.Config) (int, error) {
как cfg переменная тут используется?

2023-01-10 10:24 UTC, Bazys commented on internal/usecase/repo/shortenerpostgres.go
> +	row := d.DB.QueryRowContext(ctx, `WITH e AS (INSERT INTO url_storage (short, short_number, long, user_id)
а смысл такой сложной конструкции?

2023-01-10 10:24 UTC, Bazys commented on internal/usecase/repo/shortenermap.go
>  	mx sync.RWMutex
зачем RW мьютекс, если ты не используешь разные локи?

2023-01-10 10:24 UTC, Bazys commented on internal/app/app.go
> +		repo,
в идеале ты сюда должен передавать один единственный интерфейс, который, в зависимости от флага, создан от структуры для работы с файлом или структуры для работы с БД

2023-01-11 06:38 UTC, msjai commented on internal/app/app.go
> +func initDBTables(pgRepoS *repo.PGRepoS, cfg *config.Config) {
перенес в пакет repo

2023-01-11 06:38 UTC, msjai commented on internal/app/migrate.go
> +package app
их тоже перенес в пакет repo

2023-01-11 06:39 UTC, msjai commented on cmd/shortener/main.go
внедрил сортировку goimport

2023-01-11 06:50 UTC, msjai commented on internal/controller/shortener.go
>  	var reader io.Reader
сделал кавычки двойные

2023-01-11 06:53 UTC, msjai commented on internal/controller/shortener.go
> +func getUserID(r *http.Request, w http.ResponseWriter, URLString string, cfg *config.Config) (string, bool, error) {
переименовал

2023-01-11 06:56 UTC, msjai commented on internal/controller/shortener.go
>  	longURLString := string(b[:])
убрал

2023-01-11 06:57 UTC, msjai commented on internal/usecase/repo/shortenerpostgres.go
> +func (d *PGRepoS) findMaxNumber(ctx context.Context, cfg *config.Config) (int, error) {
убрал

2023-01-11 06:58 UTC, msjai commented on internal/usecase/repo/shortenerpostgres.go
> +	row := d.DB.QueryRowContext(ctx, `WITH e AS (INSERT INTO url_storage (short, short_number, long, user_id)
это обсудили на 1-1, по другому не получилось использовать On Conflict

2023-01-11 07:18 UTC, msjai commented on internal/usecase/repo/shortenermap.go
>  	mx sync.RWMutex
Я использую RLock(). Как я понял RLock() блокирует мап на запись, при этом не блокирует на чтение. Если конечно я правильно понял...? Поэтому использую как раз RWMutex. В описании говоррится "RLock locks rw for reading.
It should not be used for recursive read locking; a blocked Lock call excludes new readers from acquiring the lock. See the documentation on the RWMutex type."

Или RLock() блокирует на чтение мой мап? Я не совсем тогда понимаю как рабоает.
Я вот эту статью на хабре читал: https://habr.com/ru/post/338718/

"В стандартной библиотеке для решения этой ситуации есть тип [sync.RWMutex](https://golang.org/pkg/sync/#RWMutex). Помимо Lock()/Unlock(), у RWMutex есть отдельные аналогичные методы только для чтения — RLock()/RUnlock(). Если метод нуждается только в чтении — он использует RLock(), который не заблокирует другие операции чтения, но заблокирует операцию записи и наоборот."

2023-01-11 07:27 UTC, msjai commented on internal/app/app.go
> +		repo,
поправил

2023-01-12 10:23 UTC, msjai commented on internal/usecase/repo/shortenermap.go
>  	mx sync.RWMutex
все, дошло в чем ошибка была. Прочел главу про примитивы синхронизации

2023-01-12 20:50 UTC, Bazys approved these changes

2023-01-12 20:50 UTC, Bazys commented on internal/usecase/repo/repo.go
> +		m, err = migrate.New("file://internal/usecase/repo/migrations", databaseURL)
я понял почему у тебя это не работало в тестах.
почитай в сторону embededFS

2023-01-13 03:49 UTC, merged